name: Pull Request Review Status Action
description: GitHub Action to label pull requests depending on their code review status.
author: João Brilhante

branding:
  icon: lock
  color: blue

inputs:
  github-token:
    description: The GitHub token used to authenticate with the GitHub API.
    required: true
  pull-request-number:
    description: The number of the pull request to label.
    required: true

runs:
  using: node20
  main: dist/index.js
