name: Pull Request Review Status Action
description: GitHub Action to tag pull requests depending on their code review status.
author: João Brilhante

branding:
  icon: lock
  color: blue

inputs:
  milliseconds:
    description: The time to wait (in milliseconds)
    required: true
    default: "1000"

outputs:
  time:
    description: The date and time after the execution

runs:
  using: node20
  main: dist/index.js
