name: Pull Request Review Status Action
description: GitHub Action to label pull requests depending on their code review status.
author: João Brilhante

branding:
  icon: lock
  color: blue

inputs:
  github-token:
    description: The GitHub token used to authenticate with the GitHub API.
    required: true
  pull-number:
    description: The number of the pull request to label.
    required: true
  pending-review-label:
    description: The label to use when a PR is pending review.
    required: false
    default: Pending review
  changes-requested-label:
    description: The label to use when a PR needs changes.
    required: false
    default: Changes requested
  approved-label:
    description: The label to use when a PR is approved.
    required: false
    default: Approved
  min-required-approvals:
    description: The minimum number of approvals to approve a PR.
    required: false
    default: "1"

runs:
  using: node20
  main: dist/index.js
