name: Pull Request - Report

on:
  # When manually triggered
  workflow_dispatch:

  # Every day at 12:00 UTC
  schedule:
    - cron: 0 12 * * *

permissions:
  pull-requests: read # To list the open pull requests
  checks: read # To list the check runs of a pull request

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Report the pull requests
        uses: JoaoBrlt/pull-request-review-status-action@v1
        with:
          # Common
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-mode: report
          required-approvals: 1

          # Report mode
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: "#notifications"
          stale-days: 7
