name: Pull Request - Label

on:
  # When manually triggered
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: Pull request number
        required: true
        type: string

  # When a pull request is opened, synchronized, reopened, marked as ready for review, converted to draft
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "ready_for_review", "converted_to_draft"]

  # When a pull request review is submitted, edited, or dismissed
  pull_request_review:
    types: ["submitted", "edited", "dismissed"]

permissions:
  pull-requests: write # To label pull requests

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ inputs.pull_request_number || github.event.pull_request.number }}
          pending-review-label: Pending review
          changes-requested-label: Changes requested
          approved-label: Approved
          min-required-approvals: 1
